# File name: makefile
# Author: Pradeep Singh
# Date: 11/4/2018
# Description: To automate the compilation of "ping-pong.c" program.
CC = mpicc

ping-pong: ping-pong.c
        $(CC) -Wall -Werror -o ping-pong ping-pong.c

clean:
        rm ping-pong
